apiVersion: apps/v1 #deployment is inside this bucket of different objects
kind: Deployment #kind of object that we want to create
metadata:
  name: client-depl
spec:
  replicas: 1 #Replicas is the number of pods that we want to create running some particular image.
  selector:
    matchLabels: #This selector is saying, look at all the different pods that have been created. Find pods with this label
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: 268prajjwal/client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
