apiVersion: apps/v1 #deployment is inside this bucket of different objects
kind: Deployment #kind of object that we want to create
metadata:
  name: query-depl
spec:
  replicas: 1 #Replicas is the number of pods that we want to create running some particular image.
  selector:
    matchLabels: #This selector is saying, look at all the different pods that have been created. Find pods with this label
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: 268prajjwal/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
